apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-lbuw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-lbuw
    app.kubernetes.io/part-of: test-app-iotl
  name: test-component-lbuw
  namespace: build-e2e-jcgu-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: test-component-lbuw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: test-component-lbuw
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:c2b5741cb323c8dd5c89c0999c1f30cda05e60322a5a3e9a641c3f7995d8862d
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
